### ISSUE TITLE
Developer key is invalid

### ISSUE THREAD

**Issue by Keberdle** [kerrickstaley/drive-podcast#1]
Hi,
please help me i get this error when I ctry choose directory:
Developer key is invalid

What API need this script?
Developer keys is:
OAuth: Client secret
OR
API key?

**Comment by kerrickstaley** [comment]
You need to get your own developer key and insert it on line 4 of this file: https://github.com/kerrickstaley/drive-podcast/blob/master/index.html

See https://developers.google.com/drive/api/v3/quickstart/js for more information.
